### ISSUE TITLE
initChannel is not working

### ISSUE THREAD

**Issue by ghouloo** [aws-samples/lambda-java-blockchain#1]
Hi,

Not sure if i missed any configuration or this is jar dependency issue. initChannel never worked for me. Please let me know if you need any additional details.

at com.lambdajavablockchain.service.ManagedBlockchainService.initChannel(ManagedBlockchainService.java:146) ~[task/:na]
--
at com.lambdajavablockchain.controller.ApiController.queryFabcar(ApiController.java:169) ~[task/:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

2021-10-31 11:31:53.445 DEBUG 8 --- [           main] i.g.n.s.i.n.u.i.NativeLibraryLoader      : Unable to load the library 'netty_tcnative_linux_x86_64_fedora', trying next name...

java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative_linux_x86_64_fedora

**Comment by bishesh16** [comment]
Hi @ghouloo,  are you still facing the issue? I'm closing this as it is quite old now. Feel free to re-open the issue  with more details on how to reproduce. 
Thanks
